CREATE OR REPLACE TRIGGER prevent_shadow_drop
BEFORE DROP ON SHADOW.SCHEMA
BEGIN
IF ORA_DICT_OBJ_OWNER = 'SHADOW'
  AND ORA_LOGIN_USER NOT IN ('SYS','SYSTEM')
THEN
  RAISE_APPLICATION_ERROR(-20000, ORA_DICT_OBJ_OWNER
    || ' can not drop ' || ORA_DICT_OBJ_TYPE || 'S.');
END IF; 
END;
/